__author__ = "Nisheeth Barthwal"
__license__ = "GPL"
__version__ = "5.1.0.0"
__codename__ = "Ubiquity"
__date__ = "Jan 12, 2012"
__maintainer__ = "Nisheeth Barthwal"
__email__ = "me@nbaztec.co.in"
__status__ = "Public Beta"
